# All values here can be overwritten by environment variables
# with CONFIG_<key> format.

# ID of this node. Should be unique.
node_id: 'main'
# Engine used. Default is 'docker'.
engine: 'docker'
# Listen port.
port: 3000

# Security
# Supported types: 'none', 'auth_token'
auth: 'none'