services:
  nsm:
    build: .
    volumes:
      - "./dev/templates:/data/resources/templates:ro"
      - "./dev/config.yml:/data/resources/config.yml:ro"
      - "./tests:/data/tests:ro"
    ports:
      - "3000:3000"
    extra_hosts:
      - "docker.host.internal:host-gateway"
    environment:
      - "CONFIG_DOCKER_HOST=http://docker:2375"
      - "CONFIG_RESOURCES_PATH=/data/resources"
      - "DATABASE_URL=mysql://root:test@db:3306/nsm"
      - "DOCKER_HOST=tcp://docker:2375"
      - "DEBUG=${DEBUG:-false}"
    depends_on:
      db:
        condition: service_healthy
      docker:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - ./service_logs
            - ./logs
            - ./node_packages
            - ./package-lock.json
  docker:
    image: docker:29.1.3-dind
    privileged: true
    volumes:
      - docker_data:/var/lib/docker
    environment:
      # in dev environment, we don't need TLS for Dind.
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "2377:2375"
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  db:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: nsm
    ports:
      - "3306:3306"
    volumes:
      - nsm_db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ptest"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  nsm_db:
  docker_data: