name: ''
description: ''
port_range:
  min: 25565
  max: 35565
defaults:
  ram: 1024 # MB
  cpu: 2 # cores
# Optional ENV vars, and their default values
env:
  STARTUP_FILE: 'server.jar'
  # REQUIRED_OPTION: ''