name: "Minecraft"
description: "Minecraft template"
port_range:
  min: 22222
  max: 33333
meta:
  internal/stop-command: "stop"
# Args, and their default values
args:
  eula: "TRUE"
  version: "1.20.4"
container:
  env:
    EULA: "${args.eula}"
    SERVER_PORT: "${service.port}"
    VERSION: "${args.version}"
  resources:
    limits:
      ram: 4096000000
      cpu: 2
      disk: 2000000000